version: '3.8'

services:
  nginx:
    build: .
    container_name: nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./modsecurity.conf:/etc/nginx/modsecurity.conf
      - ./owasp-crs:/etc/nginx/owasp-crs
      - ./sites-enabled:/etc/nginx/sites-enabled
      - ./log:/var/log/nginx
      - ./certfile:/cert
    networks:
      - proxy_network
    #command: ["/bin/bash", "-c", "service fail2ban start && nginx -g 'daemon off;'"]

networks:
  proxy_network:
    driver: bridge
